// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerLibrary.Data;

#nullable disable

namespace ServerLibrary.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250515161926_InitialMigrationNew")]
    partial class InitialMigrationNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseLibrary.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "British author",
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6507),
                            DateOfBirth = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "J.K. Rowling",
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6508)
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Science fiction author",
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6513),
                            DateOfBirth = new DateTime(1920, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Isaac Asimov",
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6513)
                        });
                });

            modelBuilder.Entity("BaseLibrary.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<long>("ISBN")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            AvailableCopies = 5,
                            BookCode = "1001",
                            CoverImageUrl = "https://example.com/harrypotter.jpg",
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6537),
                            Description = "A young wizard's journey begins.",
                            GenreId = 1,
                            ISBN = 9780747532699L,
                            Language = "English",
                            PageCount = 223,
                            PublishedDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Philosopher's Stone",
                            TotalCopies = 5,
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6537)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            AvailableCopies = 3,
                            BookCode = "1002",
                            CoverImageUrl = "https://example.com/foundation.jpg",
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6543),
                            Description = "The story of the Galactic Empire's fall and rebirth.",
                            GenreId = 2,
                            ISBN = 9780553293357L,
                            Language = "English",
                            PageCount = 255,
                            PublishedDate = new DateTime(1951, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Foundation",
                            TotalCopies = 3,
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6543)
                        });
                });

            modelBuilder.Entity("BaseLibrary.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6236),
                            Description = "Fantasy books",
                            Name = "Fantasy",
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6239)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6241),
                            Description = "Sci-fi books",
                            Name = "Science Fiction",
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6242)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6243),
                            Description = "Romantic novels",
                            Name = "Romance",
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6243)
                        });
                });

            modelBuilder.Entity("BaseLibrary.Entities.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6618),
                            DueDate = new DateTime(2025, 5, 29, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6612),
                            Status = "Reserved",
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6618),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6622),
                            DueDate = new DateTime(2025, 5, 29, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6621),
                            Status = "Reserved",
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6622),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BaseLibrary.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BaseLibrary.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TotalReadBooks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6577),
                            Email = "alice@example.com",
                            FullName = "Alice Johnson",
                            PasswordHash = "hashedpassword",
                            PhoneNumber = "1234567890",
                            Role = "User",
                            TotalReadBooks = 0,
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6574),
                            Username = "alice"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Maple Ave",
                            CreatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6581),
                            Email = "bob@example.com",
                            FullName = "Bob Smith",
                            PasswordHash = "hashedpassword",
                            PhoneNumber = "0987654321",
                            Role = "User",
                            TotalReadBooks = 0,
                            UpdatedAt = new DateTime(2025, 5, 15, 16, 19, 25, 765, DateTimeKind.Utc).AddTicks(6579),
                            Username = "bob"
                        });
                });

            modelBuilder.Entity("BaseLibrary.Entities.Book", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Penalty", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Book", "Book")
                        .WithMany("Penalties")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Entities.User", "User")
                        .WithMany("Penalties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Reservation", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Review", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Book", b =>
                {
                    b.Navigation("Penalties");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BaseLibrary.Entities.User", b =>
                {
                    b.Navigation("Penalties");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
